import { TokenProvider } from "@/context/TokenContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navbar from "@/components/navbar/index";
import  { Toaster } from 'react-hot-toast';
import  { SWRConfig } from 'swr';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <TokenProvider>
            <Toaster />
            <Navbar />
            {children}
          </TokenProvider>
        </Providers>
      </body>
    </html>
  );
}
