export const serverConfig = {
  fetchTokenPrice: process.env.NEXT_PUBLIC_PROJECT_ID,
  apiURL: process.env.NEXT_PUBLIC_API_URL,
  SWAP_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_SWAP_CONTRACT_ADDRESS,
  ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_POLYGON_MAINNET_CONTRACT_ADDRESS,
  MATIC_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_MATIC_TOKEN_ADDRESS,
  USDT_TOKEN_ADDRESS: process.env.NEXT_PUBLIC_USDT_TOKEN_ADDRESS,
  CHAIN_ID: process.env.NEXT_PUBLIC_POLYGON_MAINNET_CHAIN_ID,
  TEST_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_TEST_CONTRACT_ADDRESS,
  ONE_INCH_ABI: require('../../abi/swap.json'),
  ERC_20_ABI: require('../../abi/IERC20.json'),
};
