export const serverConfig = {
  fetchTokenPrice: process.env.NEXT_PUBLIC_PROJECT_ID,
  apiURL: process.env.NEXT_PUBLIC_API_URL,
  SWAP_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_SWAP_CONTRACT_ADDRESS,
  ALCHEMY_API_KEY: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY,
  API_URL: process.env.NEXT_PUBLIC_API_URL,
  CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_POLYGON_MAINNET_CONTRACT_ADDRESS,
};
